# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
