# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.Report'),
        ),
    ]
